PRINT_TRIP_JS = r'''async function printTrip(scna,mode){
  const d=await api('/api/scna-detail/'+encodeURIComponent(scna));
  const x=d.trip||{};
  const w=window.open('','_blank'); if(!w)return;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const n=v=>{const z=Number(v||0);return Number.isFinite(z)?z:0};
  const fmt=v=>n(v).toLocaleString('en-US',{maximumFractionDigits:2});
  const dateOnly=v=>{if(!v)return '';const s=String(v);if(/^\d{4}-\d{2}-\d{2}/.test(s)){const a=s.slice(0,10).split('-');return `${a[2]} / ${a[1]} / ${a[0]}`;}return s;};
  const premium=n(x.exit_premium),allowance=n(x.exit_allowance),dock=n(x.dock_fee),port=n(x.port_fee);
  const commercialL=n(x.exit_commercial_fuel_liters),commercialT=n(x.exit_commercial_fuel_total);
  const officialL=n(x.exit_official_fuel_liters),officialT=n(x.exit_official_fuel_total);
  const baghdadL=n(x.exit_baghdad_fuel_liters),baghdadT=n(x.exit_baghdad_fuel_total);
  const gateFee=n(x.port_gate_exit_fee),other=n(x.exit_other),sonar=n(x.sonar);
  const totalExpenses=premium+allowance+dock+port+commercialT+officialT+baghdadT+gateFee+other+sonar;
  const freight=n(x.freight_total||x.excel_freight_au),freightRate=n(x.freight_rate),weight=n(x.net_kg),tank=n(x.tank_start_liters);
  const roadFuel=n(x.road_fuel_total),entryExtra1=n(x.entry_extra_expense_1),entryExtra2=n(x.entry_extra_expense_2),entryExtra3=n(x.entry_extra_expense_3);
  const entryExtras=entryExtra1+entryExtra2+entryExtra3,returnExpenses=roadFuel+entryExtras,driverMustReturn=freight-returnExpenses,routeKm=n(x.planned_km_go);
  const tripDate=dateOnly(x.trip_date||x.exit_at),arrivalDate=dateOnly(x.entry_display_at||x.entry_at||x.delivery_time);
  const rows=[
    ['1','Premium & Subsistence','المنحة / البريميوم و الاعاشة','-',premium+allowance],['2','Dock Management Fee (OFFLOAD)','أجور تفريغ البضاعة','-',dock],['3','Port Dock Fee (LOADING)','أجور تحميل البضاعة','-',port],['4','Commercial Fuel - Ltr','مادة الديزل التجاري',commercialL?fmt(commercialL):'-',commercialT],['5','Official Fuel - Ltr','مادة الديزل الرسمي',officialL?fmt(officialL):'-',officialT],['6','Baghdad Fuel - Ltr','مادة الديزل بغداد',baghdadL?fmt(baghdadL):'-',baghdadT],['7','Port Gate Exit Officer Fee','أجور ضابط منفذ الميناء','-',gateFee],['8','Other','أخرى','-',other],['9','Sonar','سنار','-',sonar]
  ];
  const doc=`<!doctype html><html><head><meta charset="utf-8"><title>${esc(x.scna||'')} - Shipment Form</title><style>
  @page{size:A4 portrait;margin:10mm 15mm}
  *{box-sizing:border-box}html,body{margin:0;padding:0;background:#ddd;color:#000;font-family:Arial,Tahoma,sans-serif}
  .toolbar{width:150mm;margin:5px auto;display:flex;justify-content:flex-end}.toolbar button{background:#111;color:#fff;border:0;padding:9px 16px;font-weight:800;cursor:pointer}
  .sheet{width:150mm;height:260mm;margin:10mm auto 8px;background:#fff;padding:2mm;box-shadow:0 2px 12px #0003;overflow:hidden}
  .head{border:1.4px solid #111;display:grid;grid-template-columns:29mm minmax(0,1fr) 38mm;height:48mm}
  .logoBox{border-right:1px solid #111;padding:1.5mm;display:flex;align-items:center;justify-content:center;overflow:hidden}.logoBox img{max-width:26mm;max-height:42mm;width:100%;height:100%;object-fit:contain;filter:grayscale(1) contrast(1.8)}
  .brandBox{display:grid;grid-template-rows:1fr 11mm;min-width:0;overflow:hidden}.brandMain{display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;min-width:0;padding:0 1mm}.brandMain b{font-size:25px;line-height:1;font-weight:900;letter-spacing:-.5px;max-width:100%;white-space:normal;overflow-wrap:break-word}.brandMain .ar{font-size:23px;font-weight:900;margin-top:3px;direction:rtl;max-width:100%}.brandMain small{font-size:7.5px;font-weight:800;margin-top:3px;max-width:100%;white-space:normal;line-height:1.05}
  .dateRow{border-top:1px solid #111;display:grid;grid-template-columns:24mm minmax(0,1fr);align-items:center;min-width:0}.dateLabel{text-align:center;font-weight:900;font-size:11px}.dateLabel small{font-size:10px;margin-left:3px}.dateVal{text-align:center;font-weight:900;font-size:18px;white-space:nowrap;overflow:hidden}
  .qrBox{border-left:1px solid #111;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:1mm;min-width:0;overflow:hidden}.qrTitle{font-size:10.5px;font-weight:900;max-width:100%;white-space:normal;line-height:1.05}.qrNo{font-size:21px;font-weight:900;margin:1px 0;max-width:100%;overflow:hidden}.qrBox img{width:25mm;height:25mm;object-fit:contain;max-width:100%}
  .tripInfo{border:1.4px solid #111;border-top:0;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));height:37mm}.tripCell{border-right:1px solid #111;border-bottom:1px solid #111;text-align:center;height:18.5mm;min-width:0;overflow:hidden}.tripCell:nth-child(3n){border-right:0}.tripCell:nth-last-child(-n+3){border-bottom:0}.tripLabel{font-size:10px;font-weight:900;padding:1.3mm .7mm .5mm;white-space:normal;line-height:1.05}.tripLabel span{direction:rtl;margin-left:4px}.tripVal{font-size:15px;font-weight:900;padding:.6mm 1mm;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:100%}
  table{border-collapse:collapse;width:100%;table-layout:fixed;margin-top:1.5mm;border:1.4px solid #111}th,td{border:1px solid #111;height:7.2mm;padding:.7mm 1.2mm;font-size:9.2px}th{height:8.5mm;font-size:9.2px;text-align:center;white-space:normal;line-height:1.05}.no{width:6%;text-align:center;font-weight:800}.detail{width:51%;overflow:hidden}.price{width:21%;text-align:center;font-size:11px;font-weight:800}.amt{width:22%;text-align:right;font-weight:900;font-size:12px}.detail .en{font-weight:800}.detail .ar{float:right;direction:rtl;font-size:9.2px}.total td{font-weight:900;font-size:11px;height:8mm}.total .label{text-align:center}
  .summary{margin-top:1.5mm;border:1.4px solid #111}.srow{display:grid;grid-template-columns:57% 21% 22%;height:6.8mm;border-bottom:1px solid #111}.srow:last-child{border-bottom:0}.srow>div{padding:.8mm 1.4mm;border-right:1px solid #111;font-size:8.7px;display:flex;align-items:center;min-width:0;overflow:hidden}.srow>div:last-child{border-right:0}.slab{font-weight:900;justify-content:space-between;gap:2px}.slab span:last-child{direction:rtl}.sval{justify-content:flex-end;font-weight:900!important;font-size:12px!important}
  .money{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));border:1.4px solid #111;margin-top:1.5mm;height:22mm}.mb{text-align:center;border-right:1px solid #111;padding:1.2mm;min-width:0;overflow:hidden}.mb:last-child{border-right:0}.mt{font-weight:900;font-size:9.5px;white-space:normal;line-height:1.05}.mar{direction:rtl;font-weight:800;font-size:9.5px;margin-top:1px;white-space:normal;line-height:1.05}.mv{font-size:21px;font-weight:900;margin-top:1.5mm;white-space:nowrap;overflow:hidden}
  .signs{display:grid;grid-template-columns:1fr 1fr;border:1.4px solid #111;margin-top:1.5mm;height:24mm}.sig{padding:1.5mm 4mm;text-align:center;font-size:9.5px;font-weight:900;min-width:0;overflow:hidden}.sig:first-child{border-right:1px solid #111}.sig .ar{direction:rtl;margin-left:4px}.sigline{border-top:1px solid #111;margin-top:9mm;padding-top:1mm}.dateblank{margin-top:.7mm;font-weight:800}
  @media print{html,body{width:210mm;height:297mm;background:#fff}.toolbar{display:none}.sheet{width:150mm;height:260mm;margin:0 auto;padding:1.5mm;box-shadow:none;overflow:hidden;page-break-after:avoid;break-after:avoid}.head,.tripInfo,table,.summary,.money,.signs{break-inside:avoid;page-break-inside:avoid}}
  </style></head><body><div class="toolbar"><button onclick="window.print()">YAZDIR / PDF</button></div><div class="sheet">
  <div class="head"><div class="logoBox"><img src="/api/print-logo" alt="Nukhbat Al-Nahrain"></div><div class="brandBox"><div class="brandMain"><b>NUKHBAT AL-NAHRAIN</b><div class="ar">نخبة النهرين</div><small>TRANSPORTATION &amp; MARITIME SERVICES &amp; LOGISTICS SUPPORT</small></div><div class="dateRow"><div class="dateLabel">DATE <small>التاريخ</small></div><div class="dateVal">${esc(tripDate)}</div></div></div><div class="qrBox"><div class="qrTitle">SHIPMENT No. (SNCA)</div><div class="qrNo">${esc(x.scna||'')}</div><img src="/api/print-qr/${encodeURIComponent(x.scna||'')}" alt="QR"></div></div>
  <div class="tripInfo"><div class="tripCell"><div class="tripLabel">PLATE <span>رقم اللوحة</span></div><div class="tripVal">${esc(x.plate||'')}</div></div><div class="tripCell"><div class="tripLabel">DRIVER <span>السائق</span></div><div class="tripVal">${esc(x.driver_name||'')}</div></div><div class="tripCell"><div class="tripLabel">PHONE <span>الهاتف</span></div><div class="tripVal">${esc(x.phone||'')}</div></div><div class="tripCell"><div class="tripLabel">DELIVERY AREA - KM <span>المنطقة - الكم</span></div><div class="tripVal">${esc(x.area_name||'')}${routeKm?` - ${fmt(routeKm)} KM`:''}</div></div><div class="tripCell"><div class="tripLabel">CUSTOMER <span>اسم الموكل</span></div><div class="tripVal">${esc(x.customer_name||'')}</div></div><div class="tripCell"><div class="tripLabel">ARRIVAL DATE <span>تاريخ الوصول</span></div><div class="tripVal">${esc(arrivalDate)}</div></div></div>
  <table><thead><tr><th class="no">NO.</th><th class="detail">DETAILS &nbsp; التفصيل</th><th class="price">UNIT PRICE / PRICE<br>سعر الوحدة / السعر</th><th class="amt">AMOUNT<br>المبلغ</th></tr></thead><tbody>${rows.map(r=>`<tr><td class="no">${r[0]}</td><td class="detail"><span class="en">${r[1]}</span><span class="ar">${r[2]}</span></td><td class="price">${r[3]}</td><td class="amt">${fmt(r[4])}</td></tr>`).join('')}<tr class="total"><td colspan="2" class="label">TOTAL EXPENSES &nbsp;&nbsp; مجموع المصاريف</td><td></td><td class="amt">${fmt(totalExpenses)}</td></tr></tbody></table>
  <div class="summary"><div class="srow"><div class="slab"><span>OTHER EXPENSE</span><span>مصاريف أخرى</span></div><div></div><div class="sval">${fmt(other)}</div></div><div class="srow"><div class="slab"><span>DIESEL IN TANK (Ltr)</span><span>بقي الديزل في الخزان</span></div><div></div><div class="sval">${fmt(tank)}</div></div><div class="srow"><div class="slab"><span>FREIGHT</span><span>النقل</span></div><div></div><div class="sval">${fmt(freightRate)}</div></div><div class="srow"><div class="slab"><span>WEIGHT (KG)</span><span>الوزن</span></div><div></div><div class="sval">${fmt(weight)}</div></div><div class="srow"><div class="slab"><span>TOTAL FREIGHT</span><span>مجموع النقل</span></div><div></div><div class="sval">${fmt(freight)}</div></div><div class="srow"><div class="slab"><span>ROAD FUEL EXPENSE</span><span>مصاريف وقود الطريق</span></div><div></div><div class="sval">${fmt(roadFuel)}</div></div><div class="srow"><div class="slab"><span>RETURN EXTRA EXPENSES</span><span>مصاريف العودة الإضافية</span></div><div></div><div class="sval">${fmt(entryExtras)}</div></div><div class="srow"><div class="slab"><span>DRIVER MUST RETURN</span><span>المبلغ الذي يجب على السائق تسليمه</span></div><div></div><div class="sval">${fmt(driverMustReturn)}</div></div></div>
  <div class="money"><div class="mb"><div class="mt">TOTAL FREIGHT</div><div class="mar">مجموع النقل</div><div class="mv">${fmt(freight)}</div></div><div class="mb"><div class="mt">RETURN EXPENSES</div><div class="mar">مصاريف العودة</div><div class="mv">${fmt(returnExpenses)}</div></div><div class="mb"><div class="mt">DRIVER MUST RETURN</div><div class="mar">المبلغ الذي يجب على السائق تسليمه</div><div class="mv">${fmt(driverMustReturn)}</div></div></div>
  <div class="signs"><div class="sig">DRIVER SIGNATURE <span class="ar">توقيع السائق</span><div class="sigline"></div><div class="dateblank">DATE &nbsp; التاريخ &nbsp;&nbsp; / &nbsp;&nbsp; /</div></div><div class="sig">SUPERVISOR SIGNATURE <span class="ar">توقيع المشرف</span><div class="sigline"></div><div class="dateblank">DATE &nbsp; التاريخ &nbsp;&nbsp; / &nbsp;&nbsp; /</div></div></div>
  </div></body></html>`;w.document.open();w.document.write(doc);w.document.close();
}
'''